[
    {
        "CompanyId":  5267,
        "AddressId":  6323,
        "Acronym":  "MIRIONS",
        "Name1":  "Rowery Mirions sp. z o.o.",
        "Nip":  "6770065406",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Al. Jana Pawła II 40",
        "Address2":  "",
        "PostalCode":  "31-864",
        "City":  "Kraków",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5268,
        "AddressId":  6324,
        "Acronym":  "DEMON",
        "Name1":  "DEMON Electronics s. c.",
        "Nip":  "7960038303",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Kościuszki 24/5",
        "Address2":  "",
        "PostalCode":  "44-100",
        "City":  "Gliwice",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  "śląskie"
    },
    {
        "CompanyId":  5269,
        "AddressId":  6325,
        "Acronym":  "BOHLERS",
        "Name1":  "Bonlers Press S.A.",
        "Nip":  "3444977358",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Radwańska 62",
        "Address2":  "",
        "PostalCode":  "90-453",
        "City":  "Łódź",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5270,
        "AddressId":  6326,
        "Acronym":  "FEREE",
        "Name1":  "Feree Sklep Odzieżowy s.c.",
        "Nip":  "4599771439",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Plac Szwaczek 3",
        "Address2":  "",
        "PostalCode":  "26-600",
        "City":  "Radom",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5272,
        "AddressId":  6328,
        "Acronym":  "KALLIXOS",
        "Name1":  "Kallixos Travels sp z. o.o.",
        "Nip":  "3776899915",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Joanny Żubrowej 12",
        "Address2":  "",
        "PostalCode":  "94-025",
        "City":  "Łódź",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5273,
        "AddressId":  6329,
        "Acronym":  "SUGIT",
        "Name1":  "FH Sugit Jubilier sp. z o.o.",
        "Nip":  "4245927921",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Przasnyska 12/B",
        "Address2":  "",
        "PostalCode":  "01-754",
        "City":  "Warszawa",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5275,
        "AddressId":  6331,
        "Acronym":  "JNI",
        "Name1":  "Jan Nowak IMPEX sp. z o.o.",
        "Nip":  "7875743288",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "JP II 2/4",
        "Address2":  "",
        "PostalCode":  "22-309",
        "City":  "Warszawa",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5276,
        "AddressId":  6332,
        "Acronym":  "RINNEK",
        "Name1":  "Rinnek RTV i AGD sp. z o.o.",
        "Nip":  "1424592393",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Szewska 18",
        "Address2":  "",
        "PostalCode":  "31-009",
        "City":  "Kraków",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5277,
        "AddressId":  6333,
        "Acronym":  "AMBROMODA",
        "Name1":  "AMBRO MODA sp. z. o.o.",
        "Nip":  "3781221624",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Bartoszewskiego 24",
        "Address2":  "",
        "PostalCode":  "22-345",
        "City":  "Jutrosin",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5278,
        "AddressId":  6334,
        "Acronym":  "REWASO",
        "Name1":  "REWASO Obuwie s. c.",
        "Nip":  "2184364143",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Fitelberga 22",
        "Address2":  "",
        "PostalCode":  "40-588",
        "City":  "Katowice",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5280,
        "AddressId":  6336,
        "Acronym":  "ZMP",
        "Name1":  "ZMP Kiosks s. c.",
        "Nip":  "4984942186",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "ul. Witkiewicza 3",
        "Address2":  "",
        "PostalCode":  "44-100",
        "City":  "Gliwice",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  "śląskie"
    },
    {
        "CompanyId":  5281,
        "AddressId":  6337,
        "Acronym":  "GREYFOX",
        "Name1":  "Greyfox sp. z o.o.",
        "Nip":  "9273626737",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Targowa 22",
        "Address2":  "",
        "PostalCode":  "08-400",
        "City":  "Garwolin",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5282,
        "AddressId":  6338,
        "Acronym":  "MATCHTRADE",
        "Name1":  "PH Matchtrade Sp. z o.o.",
        "Nip":  "9735911976",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Jagieńskiego 55 / 2",
        "Address2":  "",
        "PostalCode":  "38-200",
        "City":  "Jasło",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5283,
        "AddressId":  6339,
        "Acronym":  "FAJEX",
        "Name1":  "PPHU Fajex Sp. z o.o.",
        "Nip":  "9545128931",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Hutnicza 55 / 1",
        "Address2":  "",
        "PostalCode":  "44-100",
        "City":  "Gliwice",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  "śląskie"
    },
    {
        "CompanyId":  5284,
        "AddressId":  6340,
        "Acronym":  "CPL",
        "Name1":  "CP Artykuły skórzane sp. z o.o.",
        "Nip":  "5161577782",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Mickiewicza 102",
        "Address2":  "",
        "PostalCode":  "38-200",
        "City":  "Jasło",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5285,
        "AddressId":  6341,
        "Acronym":  "KIDCLOTHES",
        "Name1":  "KidClothes Sp. z o.o.",
        "Nip":  "4558231195",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "ul. K.K. Borowskiego 22",
        "Address2":  "",
        "PostalCode":  "38-200",
        "City":  "Jasło",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5291,
        "AddressId":  6347,
        "Acronym":  "MATAS",
        "Name1":  "Matas Księgarnie s. c.",
        "Nip":  "8834775949",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Kruczkowskiego 22/5",
        "Address2":  "",
        "PostalCode":  "22-500",
        "City":  "Hrubieszów",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5292,
        "AddressId":  6348,
        "Acronym":  "OLDBALLAD",
        "Name1":  "Oldballad Cafe sp. z o.o.",
        "Nip":  "3781221624",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Lwowska 152",
        "Address2":  "",
        "PostalCode":  "37-700",
        "City":  "Przemyśl",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5293,
        "AddressId":  6349,
        "Acronym":  "OVALPOWER",
        "Name1":  "Zakład usługowy Zezzom s.c.",
        "Nip":  "3781221624",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Wiśniewskiego 2",
        "Address2":  "",
        "PostalCode":  "41-922",
        "City":  "Bytom",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5294,
        "AddressId":  6350,
        "Acronym":  "KACZOR",
        "Name1":  "Andrzej Kaczor PPHU sp. z o.o.",
        "Nip":  "1182272927",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "3 Maja 12",
        "Address2":  "",
        "PostalCode":  "40-096",
        "City":  "Katowice",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5299,
        "AddressId":  6355,
        "Acronym":  "BABAKS",
        "Name1":  "BABAKS Clothes sp. z o.o.",
        "Nip":  "4284476411",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Małobądzka 45",
        "Address2":  "",
        "PostalCode":  "41-200",
        "City":  "Sosnowiec",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5301,
        "AddressId":  6357,
        "Acronym":  "GECATI",
        "Name1":  "Gecati sp. z o.o.",
        "Nip":  "4523968957",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Paderewskiego 5",
        "Address2":  "",
        "PostalCode":  "01-821",
        "City":  "Warszawa",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5302,
        "AddressId":  6358,
        "Acronym":  "ZOVCO",
        "Name1":  "Zovco sp. z o.o.",
        "Nip":  "3653249433",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Gen.W.Sikorskiego 12",
        "Address2":  "",
        "PostalCode":  "59-300",
        "City":  "Lubin",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5303,
        "AddressId":  6359,
        "Acronym":  "OLIV",
        "Name1":  "Oliv Fashion s. c.",
        "Nip":  "7331716167",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Armii Krajowej 6",
        "Address2":  "",
        "PostalCode":  "59-300",
        "City":  "Lubin",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5304,
        "AddressId":  6360,
        "Acronym":  "OJOB",
        "Name1":  "Ojob Fashion",
        "Nip":  "7923196454",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "MOSTOWA 11",
        "Address2":  "",
        "PostalCode":  "61-854",
        "City":  "Poznań",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5305,
        "AddressId":  6361,
        "Acronym":  "DAROOS",
        "Name1":  "Obuwie Daroos sp. z o.o.",
        "Nip":  "5962797777",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Dąbrowskiego 18",
        "Address2":  "",
        "PostalCode":  "59-100",
        "City":  "Kalwaria Zebrzydowska",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5306,
        "AddressId":  6362,
        "Acronym":  "SISIH",
        "Name1":  "Sisih Keebab",
        "Nip":  "7348515462",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Młyńska 6",
        "Address2":  "",
        "PostalCode":  "59-100",
        "City":  "Kalwaria Zebrzydowska",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5307,
        "AddressId":  6363,
        "Acronym":  "TEPPUS",
        "Name1":  "Teppus Shoes sp. z. o.o.",
        "Nip":  "5362276596",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "GÓRNA 8",
        "Address2":  "",
        "PostalCode":  "59-100",
        "City":  "Kalwaria Zebrzydowska",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5308,
        "AddressId":  6364,
        "Acronym":  "KIDFUN",
        "Name1":  "Kidfun S.A.",
        "Nip":  "7978145475",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Mieszka I 5",
        "Address2":  "",
        "PostalCode":  "59-323",
        "City":  "Lubin",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5309,
        "AddressId":  6365,
        "Acronym":  "IOTAALLEGRO",
        "Name1":  "Iotaallegro S.A.",
        "Nip":  "1582066717",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Skarbowców 14/5",
        "Address2":  "",
        "PostalCode":  "53-025",
        "City":  "WROCŁAW",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5310,
        "AddressId":  6366,
        "Acronym":  "YELLOWLINK",
        "Name1":  "Yellowlink Mobiles S.A.",
        "Nip":  "8124031010",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Armii Krajowej 5",
        "Address2":  "",
        "PostalCode":  "40-847",
        "City":  "Katowice",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5311,
        "AddressId":  6367,
        "Acronym":  "CEBO",
        "Name1":  "Cebo Buty sp. z o.o.",
        "Nip":  "3181533410",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Chłopowskiego 5",
        "Address2":  "",
        "PostalCode":  "80-017",
        "City":  "Gdańsk",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5312,
        "AddressId":  6368,
        "Acronym":  "XELLO",
        "Name1":  "Xello Gymn s. c.",
        "Nip":  "3698982920",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Międzyleska 22",
        "Address2":  "",
        "PostalCode":  "55-095",
        "City":  "Mirków",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5313,
        "AddressId":  6369,
        "Acronym":  "LIFETAG",
        "Name1":  "Lifetag sp. z. o.o.",
        "Nip":  "5587792301",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Storczyków  1",
        "Address2":  "",
        "PostalCode":  "00-710",
        "City":  "Warszawa",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5314,
        "AddressId":  6370,
        "Acronym":  "MUSSIR",
        "Name1":  "Mussir Burgers sp. z o.o.",
        "Nip":  "3192230535",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Krupińskiego 5",
        "Address2":  "",
        "PostalCode":  "07-200",
        "City":  "Wyszków",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5315,
        "AddressId":  6371,
        "Acronym":  "FOMODI",
        "Name1":  "Fomodi Jan Nowak",
        "Nip":  "3384161072",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Kolejowa 2",
        "Address2":  "",
        "PostalCode":  "65-770",
        "City":  "Zielona Góra",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5316,
        "AddressId":  6372,
        "Acronym":  "DEFAP",
        "Name1":  "Defap Adam Kowalewski sp. z. o.o.",
        "Nip":  "7564384901",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Srebrna 8",
        "Address2":  "",
        "PostalCode":  "30-390",
        "City":  "Kraków",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5317,
        "AddressId":  6373,
        "Acronym":  "BUFOO",
        "Name1":  "Bufoo Centrum Marcin Marcinkiewicz s. c.",
        "Nip":  "6860427600",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Krucza 64",
        "Address2":  "",
        "PostalCode":  "15-057",
        "City":  "BIAŁYSTOK",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5318,
        "AddressId":  6374,
        "Acronym":  "BKAB",
        "Name1":  "Big Kahuna Burger sp. z o.o.",
        "Nip":  "8562348830",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Andrzejewskiego 12",
        "Address2":  "",
        "PostalCode":  "70-786",
        "City":  "Szczecin",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5319,
        "AddressId":  6375,
        "Acronym":  "XOFFEX",
        "Name1":  "XOFFEX Cafee Agniszka Kowalczyk s. c.",
        "Nip":  "1159488778",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Józefitów 85 / B",
        "Address2":  "",
        "PostalCode":  "30-039",
        "City":  "Kraków",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5320,
        "AddressId":  6376,
        "Acronym":  "IGUP",
        "Name1":  "Igup Meals s. c.",
        "Nip":  "8546865677",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Wyszyńskiego 1",
        "Address2":  "",
        "PostalCode":  "42-506",
        "City":  "Będzin",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5321,
        "AddressId":  6377,
        "Acronym":  "SAMIX",
        "Name1":  "Samix Market S. A.",
        "Nip":  "2455094751",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Aleje Jerozolimskie 122",
        "Address2":  "",
        "PostalCode":  "02-001",
        "City":  "Warszawa",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5322,
        "AddressId":  6378,
        "Acronym":  "ENEL",
        "Name1":  "Meble Enel Krzysztof Antoniak s. c.",
        "Nip":  "3672576541",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Sybiraków 55",
        "Address2":  "",
        "PostalCode":  "59-300",
        "City":  "Lubin",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5323,
        "AddressId":  6379,
        "Acronym":  "POLLE",
        "Name1":  "Polle Travel sp. z o.o.",
        "Nip":  "7426157138",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Moniuszki 10",
        "Address2":  "",
        "PostalCode":  "90-011",
        "City":  "Łódź",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5324,
        "AddressId":  6380,
        "Acronym":  "VAVSI",
        "Name1":  "Vavsi Centrum sp. z o.o.",
        "Nip":  "3428177516",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "KILIŃSKIEGO 2",
        "Address2":  "",
        "PostalCode":  "59-300",
        "City":  "Lubin",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5325,
        "AddressId":  6381,
        "Acronym":  "BEZEE",
        "Name1":  "Bezee PIZZA Mariusz Zając sp. z o.o.",
        "Nip":  "5349882859",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Sikorskiego 12",
        "Address2":  "",
        "PostalCode":  "53-659",
        "City":  "Wrocław",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5326,
        "AddressId":  6382,
        "Acronym":  "PARI",
        "Name1":  "Pari Pari Ristorante sp. z o.o.",
        "Nip":  "2444142601",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Częstochowska 10",
        "Address2":  "",
        "PostalCode":  "54-072",
        "City":  "Wrocław",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5327,
        "AddressId":  6383,
        "Acronym":  "CAXXIW",
        "Name1":  "Pralnie chemiczne Caxxiw s. c.",
        "Nip":  "5245018685",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Armii Krajowej  15",
        "Address2":  "",
        "PostalCode":  "61-371",
        "City":  "Poznań",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5328,
        "AddressId":  6384,
        "Acronym":  "HOREE",
        "Name1":  "Horee sp. z o.o.",
        "Nip":  "9663945433",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Piłsudskiego  1",
        "Address2":  "",
        "PostalCode":  "50-020",
        "City":  "Wrocław",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5329,
        "AddressId":  6385,
        "Acronym":  "HERAGO",
        "Name1":  "Herago Toys S.A.",
        "Nip":  "8478397814",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Batalionów Chłopskich 10",
        "Address2":  "",
        "PostalCode":  "68-200",
        "City":  "Żary",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5330,
        "AddressId":  6386,
        "Acronym":  "RUTTO",
        "Name1":  "Rutto Electronics sp. z o.o.",
        "Nip":  "9845702067",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Księzycowa 10 / 2",
        "Address2":  "",
        "PostalCode":  "02-797",
        "City":  "Warszawa",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5331,
        "AddressId":  6387,
        "Acronym":  "POVENO",
        "Name1":  "Poveno AGD i RTV s. c.",
        "Nip":  "3760404696",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Sikorskiego 12",
        "Address2":  "",
        "PostalCode":  "01-192",
        "City":  "Warszawa",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5332,
        "AddressId":  6388,
        "Acronym":  "HUBOOO",
        "Name1":  "Hubooo Computers sp. z o.o.",
        "Nip":  "3911950340",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Młyńska 10 / 5",
        "Address2":  "",
        "PostalCode":  "60-175",
        "City":  "Poznań",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5333,
        "AddressId":  6389,
        "Acronym":  "FEHO",
        "Name1":  "Supermarket spożywczy Feho sp. z o.o.",
        "Nip":  "6725912642",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Wesoła 15",
        "Address2":  "",
        "PostalCode":  "59-140",
        "City":  "Chocianów",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5334,
        "AddressId":  6390,
        "Acronym":  "SOLLI",
        "Name1":  "Drogerie Solli S.A.",
        "Nip":  "7221834931",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Rynek 7",
        "Address2":  "",
        "PostalCode":  "45-449",
        "City":  "Opole",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5335,
        "AddressId":  6391,
        "Acronym":  "ZEFU",
        "Name1":  "Zefu Łukasz Łukasiewicz sp. z o.o.",
        "Nip":  "9441769935",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Długa 115",
        "Address2":  "",
        "PostalCode":  "62-800",
        "City":  "Kalisz",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5336,
        "AddressId":  6392,
        "Acronym":  "CLANMILE",
        "Name1":  "Clanmile S.A.",
        "Nip":  "6980673164",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Bolesława Krzywoustego 10",
        "Address2":  "",
        "PostalCode":  "40-104",
        "City":  "Katowice",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5337,
        "AddressId":  6393,
        "Acronym":  "JAWOR",
        "Name1":  "PPHU Jawor Adam sp. z o.o.",
        "Nip":  "4493463252",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Os. Czwartaków  10",
        "Address2":  "",
        "PostalCode":  "62-020",
        "City":  "Swarzędź",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5338,
        "AddressId":  6394,
        "Acronym":  "NULU",
        "Name1":  "PPHU Nulu s. c.",
        "Nip":  "8542874515",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Dworcowa 48/2",
        "Address2":  "",
        "PostalCode":  "02-214",
        "City":  "Warszawa",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5339,
        "AddressId":  6395,
        "Acronym":  "NOZUH",
        "Name1":  "PHU Nozuh s.c.",
        "Nip":  "5970650758",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Skierniewskiego 33",
        "Address2":  "",
        "PostalCode":  "66-400",
        "City":  "Gorzów Wielkopolski",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5340,
        "AddressId":  6396,
        "Acronym":  "JUVVO",
        "Name1":  "Juvvo S.A.",
        "Nip":  "1832281375",
        "IsSupplier":  false,
        "IsClient":  true,
        "Address1":  "Kościuszki 10",
        "Address2":  "",
        "PostalCode":  "30-415",
        "City":  "Kraków",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5267,
        "AddressId":  6405,
        "Acronym":  "MIRIONS",
        "Name1":  "Rowery Mirions sp. z o.o.",
        "Nip":  "6770065406",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "",
        "Address2":  "",
        "PostalCode":  "00-000",
        "City":  "Kraków",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  "małopolskie"
    },
    {
        "CompanyId":  5267,
        "AddressId":  6406,
        "Acronym":  "MIRIONS",
        "Name1":  "Rowery Mirions sp. z o.o.",
        "Nip":  "6770065406",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "ul. Puławska 525",
        "Address2":  "",
        "PostalCode":  "00-955",
        "City":  "Warszawa",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5267,
        "AddressId":  6407,
        "Acronym":  "MIRIONS",
        "Name1":  "Rowery Mirions sp. z o.o.",
        "Nip":  "6770065406",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "",
        "Address2":  "",
        "PostalCode":  "00-000",
        "City":  "Kraków",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  "małopolskie"
    },
    {
        "CompanyId":  5280,
        "AddressId":  6410,
        "Acronym":  "ZMP",
        "Name1":  "ZMP Kiosks s. c.",
        "Nip":  "4984942186",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "ul. Witkiewicza 24",
        "Address2":  "",
        "PostalCode":  "37-400",
        "City":  "Gliwice",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  "śląskie"
    },
    {
        "CompanyId":  5280,
        "AddressId":  6411,
        "Acronym":  "ZMP",
        "Name1":  "ZMP Kiosks s. c.",
        "Nip":  "4984942186",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "ul. Witkiewicza 45",
        "Address2":  "",
        "PostalCode":  "37-400",
        "City":  "Gliwice",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  "śląskie"
    },
    {
        "CompanyId":  5341,
        "AddressId":  6413,
        "Acronym":  "RAGGE",
        "Name1":  "Ragge Club sp. z o.o.",
        "Nip":  "6321921414",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "ul. Kolejowa 265",
        "Address2":  "",
        "PostalCode":  "82-500",
        "City":  "Kwidzyn",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    },
    {
        "CompanyId":  5342,
        "AddressId":  6414,
        "Acronym":  "ZOKO",
        "Name1":  "ZOKO S.A.",
        "Nip":  "7239832838",
        "IsSupplier":  true,
        "IsClient":  true,
        "Address1":  "Ogrodowa 28",
        "Address2":  "",
        "PostalCode":  "05-092",
        "City":  "Łomianki",
        "CountryCode":  "PL",
        "Country":  "Polska",
        "Province":  ""
    }
]